### ISSUE TITLE
Hook up triggers to lambdas

### ISSUE THREAD

**Issue by colbywhite** [colbywhite/why82.calc#13]
``` yaml
stats:
  - schedule: rate(daily)
tiers:
  - s3: bucket/*-stats.json
schedule:
  - s3: bucket/*-tiers.json
```

or something like that.
